http_address: :5000
db:
  user: postgres
  password: postgres
  name: postgres
  host: db
  port: 5432
jwt:
  private_file: rs256.rsa
  public_file: rs256.rsa.pub
tickenator_host: tickenator:5001
kafka:
  host: kafka:5003
stats_host: stats:5007
